pipeline:
  frontend:
    image: node:8.3.0
    group: testing
    commands:
      - echo "fontend test"


  backend:
    image: node:8.3.0
    group: testing
    commands:
      - echo "backend testing"
